### ISSUE TITLE
Error while calling Cart/Validator via console command

### ISSUE THREAD

**Issue by twaurisch** [teambank/ratenkaufbyeasycredit-plugin-shopware-6#15]
While using the console command to import orders from idealo `console ott:idealo:order:import` no ReqeustStack is available.

_console.CRITICAL: Error thrown while running command "ott:idealo:order:import". Message: "Call to a member function get() on null" {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /shopware/custom/plugins/EasyCreditRatenkauf/src/Cart/Validator.php:54)","command":"ott:idealo:order:import","message":"Call to a member function get() on null"} []_

The error was introduced with commit 7c84af10cb52d26ffe31c6bedbeb5203b84bdf40 

The import works if the line 54 has been removed from Cart/Validator.php.
```
        if (
            //!$this->requestStack->getCurrentRequest()->attributes->get('_route') || // if route is not set no controller was resolved (leading to 404) and the cart is empty
            in_array($cart->getName(), ['recalculation', 'sales-channel'])
        ) {
            return;
        }
```

**Comment by netzkollektiv** [comment]
Thank you for creating the issue. We are going to release a new version soon.
