### ISSUE TITLE
Release 2.1.1 to Shopware Store

### ISSUE THREAD

**Issue by develth** [teambank/ratenkaufbyeasycredit-plugin-shopware-6#18]
Hi

Could you please release it to shopware store? Currenty not downloadable via `store.shopware.com/easycreditratenkauf`

thanks

**Comment by netzkollektiv** [comment]
Hi,

actually we did already last week but Shopware is still reviewing it. You may just install the version from the releases page on Github in the meantime.

**Comment by develth** [comment]
thx for the quick reply
